apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wpxdvtctf-python-gitops
  description: This is GitOps manifest for wpxdvtctf-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=wpxdvtctf-python
    backstage.io/kubernetes-id: wpxdvtctf-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wpxdvtctf-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wpxdvtctf-python
